

/*
Copyright (c) 2014 Peter Harrison

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 */

#include "commands.h"
#include "testdata.h"

/*
 * Data used to test the path generator. Each pair has a string of simple
 * instructions taken from the set FLRS. The instruction list would
 * normally be generated from maze flooding data.
 *
 * The second element is an array of motion commands for the mouse. The
 * command list is zero terminated and shows the output expected to be
 * generated by the path generator.
 *
 * A single test would attempt to generate a path from the input and then
 * compare the generated path with the expected path to see if they match.
 *
 * When testing, include all the data in case fixing one test breaks
 * a test that previously passed.
 *
 * It may be useful to have an existing path generator create the expected
 * data so that the two algorithms may be compared.
 */

testPair_t testPairsSimple[] = {
  "S",
  {CMD_STOP},
  "FS",
  {FWD1, CMD_STOP},
  "FFS",
  {FWD2, CMD_STOP},
  "FFFS",
  {FWD3, CMD_STOP},
  "RS",
  {CMD_ERROR_00, CMD_STOP},
  "LS",
  {CMD_ERROR_00, CMD_STOP},
  "XS",
  {CMD_ERROR_00, CMD_STOP},
  "X",
  {CMD_ERROR_00, CMD_STOP},
  "FRS",
  {FWD1, SS90ER, FWD1, CMD_STOP},
  "FLS",
  {FWD1, SS90EL, FWD1, CMD_STOP},
  "FRFS",
  {FWD1, SS90ER, FWD2, CMD_STOP},
  "FLFS",
  {FWD1, SS90EL, FWD2, CMD_STOP},
  "FFRFS",
  {FWD2, SS90ER, FWD2, CMD_STOP},
  "FFLFS",
  {FWD2, SS90EL, FWD2, CMD_STOP},
  //
  "FFRFRS",
  {FWD2, SS90ER, FWD2, SS90ER, FWD1, CMD_STOP},
  "FFLFLS",
  {FWD2, SS90EL, FWD2, SS90EL, FWD1, CMD_STOP},
  "FFRFLS",
  {FWD2, SS90ER, FWD2, SS90EL, FWD1, CMD_STOP},
  //
  "FFRLS",
  {FWD2, SS90ER, FWD1, SS90EL, FWD1, CMD_STOP},
  "FFLRS",
  {FWD2, SS90EL, FWD1, SS90ER, FWD1, CMD_STOP},
  // sequential turns
  "FFFFRRFFFS",
  {FWD4, SS90ER, FWD1, SS90ER, FWD4, CMD_STOP},
  "FFFFLLFFFS",
  {FWD4, SS90EL, FWD1, SS90EL, FWD4, CMD_STOP},
  "FFFFRRLLFFFS",
  { FWD4, SS90ER, FWD1, SS90ER, FWD1, SS90EL, FWD1, SS90EL, FWD4, CMD_STOP},
  "FFFFLLRRFFFS",
  { FWD4, SS90EL, FWD1, SS90EL, FWD1, SS90ER, FWD1, SS90ER, FWD4, CMD_STOP},
  "FFFFRRLRFFFS",
  {FWD4, SS90ER, FWD1, SS90ER, FWD1, SS90EL, FWD1, SS90ER, FWD4, CMD_STOP},
  "FFFFLLRLFFFS",
  {FWD4, SS90EL, FWD1, SS90EL, FWD1, SS90ER, FWD1, SS90EL, FWD4, CMD_STOP},
  //
  "FFRFLRFFS",
  {FWD2, SS90ER, FWD2, SS90EL, FWD1, SS90ER, FWD3, CMD_STOP},
  "FRFFLFRLS",
  {FWD1, SS90ER, FWD3, SS90EL, FWD2, SS90ER, FWD1, SS90EL, FWD1, CMD_STOP},
};

/*
 * To avoid trying to keep count of the number of test pairs added, a
 * function returns the current count. The compiler will work out the
 * answer.
 */

int testCountSimple(void) {
  return sizeof (testPairsSimple) / sizeof (testPair_t);
}
